/**
 * This file was generated by the Jeddict
 */ 

package com.jkelsy;


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@NamedQuery(name = "Estudiante.findByCode", query = 
        "Select e from Estudiante e where e.PEOPLE_CODE_ID = :PEOPLE_CODE_ID and e.anyoLiquidacion = :anyo and e.semestre = :semestre"
)
public class Estudiante implements Serializable { 
    
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Basic private String PEOPLE_CODE_ID;
    
    @Basic private int anyoLiquidacion;
    
    @Basic private String semestre;
    
    @Basic private String nacionalidad;

    @Basic private String Nombres;
    
    @Basic private String Apellidos;

    @Basic private int estrato;
    
    @Basic private String tipoColegio; //oficial o privado

    @Basic private int patrimonio;

    @Basic private int ingreso;
    
    @Basic private int ultimoPago; //pago mensual último anyo secundaria
    
    @Basic private int ultimoAnyoPago; //último año secundaria    
    
    @Temporal(TemporalType.TIMESTAMP) private Date fechaActualizacion;
    
    @Basic private String actualizadoPor;
    
    @Basic private Boolean liquidar;

    public Boolean getLiquidar() {
        return liquidar;
    }

    public void setLiquidar(Boolean liquidar) {
        this.liquidar = liquidar;
    }

    public Date getFechaActualizacion() {
        return fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActulizacion) {
        this.fechaActualizacion = fechaActulizacion;
    }

    public String getActualizadoPor() {
        return actualizadoPor;
    }

    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }

    public int getUltimoPago() {
        return ultimoPago;
    }

    public void setUltimoPago(int ultimoPago) {
        this.ultimoPago = ultimoPago;
    }

    public int getUltimoAnyoPago() {
        return ultimoAnyoPago;
    }

    public void setUltimoAnyoPago(int ultimoAnyoPago) {
        this.ultimoAnyoPago = ultimoAnyoPago;
    }

    public int getAnyoLiquidacion() {
        return anyoLiquidacion;
    }

    public void setAnyoLiquidacion(int anyoLiquidacion) {
        this.anyoLiquidacion = anyoLiquidacion;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPEOPLE_CODE_ID() {
        return this.PEOPLE_CODE_ID;
    }

    public void setPEOPLE_CODE_ID(String PEOPLE_CODE_ID) {
        this.PEOPLE_CODE_ID = PEOPLE_CODE_ID;
    }

    public String getNombres() {
        return Nombres;
    }

    public void setNombres(String Nombres) {
        this.Nombres = Nombres;
    }

    public String getApellidos() {
        return Apellidos;
    }

    public void setApellidos(String Apellidos) {
        this.Apellidos = Apellidos;
    }

    public int getEstrato() {
        return this.estrato;
    }

    public void setEstrato(int estrato) {
        this.estrato = estrato;
    }

    public int getPatrimonio() {
        return this.patrimonio;
    }

    public void setPatrimonio(int patrimonio) {
        this.patrimonio = patrimonio;
    }

    public int getIngreso() {
        return this.ingreso;
    }

    public void setIngreso(int ingreso) {
        this.ingreso = ingreso;
    }

    public String getNacionalidad() {
        return nacionalidad;
    }

    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    public String getSemestre() {
        return semestre;
    }

    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }

    public String getTipoColegio() {
        return tipoColegio;
    }

    public void setTipoColegio(String tipoColegio) {
        this.tipoColegio = tipoColegio;
    }
}
